### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by nielsk** [geier/khal#142]
When running khal I get the following error:

    debug: using the config file at /home/foo/.config/khal/khal.conf
    debug: Using config:
    debug: [calendars]
    debug: [[home]]
    debug: path = /home/foo/.khal/calendars/home/
    debug: color = dark blue
    debug: [[work]]
    debug: path = /home/foo/.khal/calendars/home/
    debug: color = yellow
    debug:
    debug: [sqlite]
    debug: path = /home/foo/.khal/khal.db
    debug:
    debug: [locale]
    debug: timeformat = %H:%M
    debug: dateformat = %d.%m.
    debug: longdateformat = %d.%m.%Y
    debug: datetimeformat = %d.%m. %H:%M
    debug: longdatetimeformat = %d.%m.%Y %H:%M
    debug:
    debug: firstweekday = 0
    debug: weeknumbers = False
    debug: local_timezone = Europe/Berlin
    debug: default_timezone = America/New_York
    debug: encoding = utf-8
    debug: unicode_symbols = True
    debug:
    debug: [default]
    debug: default_command = calendar
    debug: default_calendar = home
    debug: show_all_days = False
    debug: created version table
    debug: created accounts table
    debug: tables for calendar home exist
    debug: created version table
    debug: created accounts table
    debug: tables for calendar work exist
    Traceback (most recent call last):
      File "/usr/bin/khal", line 9, in <module>
        load_entry_point('khal==0.4.0.dev-124-g46ae09e-dirty', 'console_scripts', 'khal')()
      File "/usr/lib/python2.7/site-packages/click/core.py", line 610, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/click/core.py", line 590, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python2.7/site-packages/click/core.py", line 916, in invoke
        return Command.invoke(self, ctx)
      File "/usr/lib/python2.7/site-packages/click/core.py", line 782, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python2.7/site-packages/click/core.py", line 416, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/khal/cli.py", line 161, in cli
        ctx.invoke(cli.commands[command])
      File "/usr/lib/python2.7/site-packages/click/core.py", line 416, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/khal/cli.py", line 182, in calendar
        events=events
      File "/usr/lib/python2.7/site-packages/khal/controllers.py", line 138, in __init__
        echo('\n'.join(rows).encode(encoding))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 452: ordinal not in range(128)

**Comment by gour** [comment]
> This should be fixed now, please reopen if the bug persists. Thanks again for reporting this!

New khal user, old problem...
```
(vdir)gour@atmarama ~/p/vdir> ikhal
Traceback (most recent call last):
  File "/home/gour/prj/vdir/bin/ikhal", line 11, in <module>
    sys.exit(main_ikhal())
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/khal/cli.py", line 315, in interactive_cli
    controllers.interactive(build_collection(ctx), ctx.obj['conf'])
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/khal/controllers.py", line 193, in interactive
    description='do something')
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/khal/ui/__init__.py", line 602, in __init__
    weeknumbers=conf['locale']['weeknumbers'],
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/khal/ui/calendarwidget.py", line 385, in __init__
    dnames = calendar.weekheader(2).split(' ')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 9: ordinal not in range(128)
(vdir)gour@atmarama ~/p/vdir> khal -v
debug: using the config file at /home/gour/.config/khal/khal.conf
debug: Using config:
debug: [calendars]
debug:   [[gour]]
debug:     path: /home/gour/prj/vdir/calendars/gour/
debug:     color: light blue
debug:     readonly: False
debug:     type: calendar
debug: [locale]
debug:   local_timezone: Europe/Zagreb
debug:   default_timezone: Europe/Zagreb
debug:   timeformat: %H:%M
debug:   dateformat: %d.%m.
debug:   longdateformat: %d.%m.%Y
debug:   datetimeformat: %d.%m. %H:%M
debug:   longdatetimeformat: %d.%m.%Y %H:%M
debug:   encoding: utf-8
debug:   firstweekday: 0
debug:   unicode_symbols: True
debug:   weeknumbers: False
debug: [sqlite]
debug:   path: /home/gour/.local/share/khal/khal.db
debug: [keybindings]
debug:   up: ['up', 'k']
debug:   down: ['down', 'j']
debug:   right: ['right', 'l', ' ']
debug:   left: ['left', 'h', 'backspace']
debug:   new: ['n']
debug:   delete: ['d']
debug:   view: ['enter', 'tab']
debug:   today: ['t']
debug:   save: ['meta enter']
debug: [default]
debug:   default_command: calendar
debug:   default_calendar: None
debug:   show_all_days: False
debug:   days: 2
debug:   print_new: False
debug: [view]
debug:   event_view_weighting: 1
debug:   event_view_always_visible: False
debug: created version table
debug: tables for calendar gour exist
    Mo Tu We Th Fr Sa Su     No events
Aug 27 28 29 30 31  1  2     
     3  4  5  6  7  8  9     
    10 11 12 13 14 15 16     
    17 18 19 20 21 22 23     
    24 25 26 27 28 29 30     
Sep 31  1  2  3  4  5  6     
     7  8  9 10 11 12 13     
    14 15 16 17 18 19 20     
    21 22 23 24 25 26 27     
Oct 28 29 30  1  2  3  4     
     5  6  7  8  9 10 11     
    12 13 14 15 16 17 18     
    19 20 21 22 23 24 25     
Nov 26 27 28 29 30 31  1     
```

Any idea?

**Comment by geier** [comment]
@gour can you please run the following in a python shell:
```
import calendar
calendar.weekheader(2)
type(calendar.weekheader(2)
```
and paste the output here?

**Comment by gour** [comment]
```
vdir)gour@atmarama ~/p/vdir> python
Python 2.7.10 (default, Jul  1 2015, 10:54:53) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import calendar
>>> calendar.weekheader(2)
'Mo Tu We Th Fr Sa Su'
>>> type(calendar.weekheader(2))
<type 'str'>
>>> 
```

**Comment by geier** [comment]
hmm, sorry no idea yet.

Could you do another one?

```
import calendar
calendar.weekheader(2).split(' ')
```

and also the fix in branch `fix_142`?

Thank you!

**Comment by gour** [comment]
> Could you do another one?

```
>>> import calendar
>>> calendar.weekheader(2).split(' ')
['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su']
```
> and also the fix in branch fix_142?

```
(vdir)gour@atmarama ~/p/vdir> ikhal 
Traceback (most recent call last):
  File "/home/gour/prj/vdir/bin/ikhal", line 11, in <module>
    sys.exit(main_ikhal())
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/khal/cli.py", line 315, in interactive_cli
    controllers.interactive(build_collection(ctx), ctx.obj['conf'])
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/khal/controllers.py", line 193, in interactive
    description='do something')
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/khal/ui/__init__.py", line 602, in __init__
    weeknumbers=conf['locale']['weeknumbers'],
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/khal/ui/calendarwidget.py", line 388, in __init__
    dnames = to_unicode(calendar.weekheader(2)).split(' ')
  File "/home/gour/prj/vdir/local/lib/python2.7/site-packages/khal/compat.py", line 28, in to_unicode
    return string.decode(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 9: ordinal not in range(128)
```

Let me add I'm on Debian Sid (x86_64), but have vdirsyncer/khal/khard installed in virtualenv...

I manually patched my installation with https://github.com/geier/khal/commit/435ff04555b6e7460afa2cbe5b56a4baf2e89f57, that's ok?

**Comment by geier** [comment]
hmmm... Do you have a non US LOCALE set? Some where the day names contain some non ascii characters?

**Comment by gour** [comment]
> Do you have a non US LOCALE set? Some where the day names contain some non ascii characters?

Yes, here is my locale output:

```
(vdir)gour@atmarama ~/p/vdir> locale
LANG=hr_HR.UTF-8
LANGUAGE=
LC_CTYPE=hr_HR.UTF-8
LC_NUMERIC=hr_HR.UTF-8
LC_TIME=hr_HR.UTF-8
LC_COLLATE=hr_HR.UTF-8
LC_MONETARY=hr_HR.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=hr_HR.UTF-8
LC_NAME=hr_HR.UTF-8
LC_ADDRESS=hr_HR.UTF-8
LC_TELEPHONE=hr_HR.UTF-8
LC_MEASUREMENT=hr_HR.UTF-8
LC_IDENTIFICATION=hr_HR.UTF-8
LC_ALL=
```

Does it mean khal cannot work with non-ascii locale?

**Comment by geier** [comment]
No, it should definitely work with other locales, but this should help me debug this. I already tried with Danish but it wouldn't raise an exception. 

Am 1. September 2015 08:26:37 MESZ, schrieb Gour <notifications@github.com>:

**Comment by geier** [comment]
Could you try the new patch from branch `fix_142` again? Thanks for being by guinea pig :)

**Comment by gour** [comment]
> Could you try the new patch from branch fix_142 again? 

Now it works...it's joy of keeping compatibility with both python 2 & 3. :-)

> Thanks for being by guinea pig :)

Thank you for giving us very useful app!

**Comment by geier** [comment]
You're welcome!

**Comment by dzoep** [comment]
I'd like to reopen this - even with latest sources I get:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./khal/cli.py", line 359, in interactive_cli
    controllers.interactive(build_collection(ctx), ctx.obj['conf'])
  File "./khal/controllers.py", line 211, in interactive
    description='do something')
  File "./khal/ui/__init__.py", line 624, in __init__
    get_styles=collection.get_styles
  File "./khal/ui/calendarwidget.py", line 522, in __init__
    weekheader = weekheader.decode('utf-8')
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 13: invalid continuation byte

My locale is cs_CZ.UTF-8 and if I add "print weekheader" to line 520 (just after weekheader = calendar.weekheader(2), I get following (ran through hexdump -C to see the problem):

00000000  50 6f 20 c3 9a 20 53 74  20 c4 8c 20 50 c3 20 53  |Po .. St .. P. S|
00000010  6f 20 4e 65 0a                                    |o Ne.|
00000015

Monday = "Po" ... ok
Tuesday = "Út" => "Ú" ... not OK, but doesn't fail (two bytes, not two unicode characters)
...
Friday = "Pá" => "P?" (50 c3) ... not OK and causes the exception seen above.

After a few experiments with calendar.weekheader I think it is broken in the python2 series.

**Comment by untitaker** [comment]
@dzoep is there a particular file that causes this exception?

**Comment by untitaker** [comment]
Actually, please create a new issue, this thread is getting too long.
