### ISSUE TITLE
UnboundLocalError: local variable 'href_rec_inst' referenced before assignment

### ISSUE THREAD

**Issue by mbaldessari** [geier/khal#171]
Maybe another Zimbra oddity ;)
I have added the company wide calendar (~2000 entries) and on a couple I get the following:
```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/khal/khalendar/khalendar.py", line 175, in _update_vevent
    self._dbtool.update(event.raw, href=href, etag=etag)
  File "/usr/lib/python2.7/site-packages/khal/khalendar/backend.py", line 253, in update
    self._update_impl(vevent, href, etag)
  File "/usr/lib/python2.7/site-packages/khal/khalendar/backend.py", line 328, in _update_impl
    etag, href, self.calendar, href_rec_inst)
UnboundLocalError: local variable 'href_rec_inst' referenced before assignment
warning: Skipping team/371c7106-c512-4f15-bcc4-47fa0e2fcafa.ics: local variable 'href_rec_inst' referenced before assignment
warning: This event will not be available in khal.
```
This is the ics file:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:Zimbra-Calendar-Provider
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETTO:+0100
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=10;BYDAY=-1SU
TZNAME:CET
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETTO:+0200
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=-1SU
TZNAME:CEST
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:371c7106-c512-4f15-bcc4-47fa0e2fcafa
RRULE:FREQ=DAILY;COUNT=2;INTERVAL=1
EXDATE;TZID="Europe/Berlin":20110908T130000
EXDATE;TZID="Europe/Berlin":20110909T130000
SUMMARY:michele ½ day PTO
X-MS-OLK-SENDER:mailto:team@acksyn.org
ORGANIZER;SENT-BY="mailto:team@acksyn.org":mailto:foo@acksyn.org
X-MS-OLK-SENDER:mailto:team@acksyn.org
DTSTART;TZID="Europe/Berlin":20110908T130000
DTEND;TZID="Europe/Berlin":20110908T170000
STATUS:CONFIRMED
CLASS:PUBLIC
TRANSP:OPAQUE
LAST-MODIFIED:20110830T135117Z
DTSTAMP:20110830T135117Z
SEQUENCE:2
END:VEVENT
END:VCALENDAR
```

Thanks again!
Michele

**Comment by geier** [comment]
I'll have a look, thanks for reporting!

**Comment by untitaker** [comment]
@mbaldessari If I'm not mistaken, your event doesn't do anything. It is specified to recur two times, but then has exceptions defined that exclude these two recurrences. It's therefore completely useless (try searching for it in another client).

I added a fix to deal with such events though.

**Comment by mbaldessari** [comment]
@untitaker It might very well be that it is some older relic someone created in Zimbra ages ago and it won't show anywhere in the web interface, but vdirsyncer fetched it nonetheless. Thanks for the fix ;)

**Comment by geier** [comment]
@untitaker thanks for taking care of this, I'm swamped at the moment.
