### ISSUE TITLE
Calendar entry being rejected and not shown

### ISSUE THREAD

**Issue by hobarrera** [geier/khal#174]
```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/khal/khalendar/khalendar.py", line 175, in _update_vevent
    self._dbtool.update(event.raw, href=href, etag=etag)
  File "/usr/lib/python2.7/site-packages/khal/khalendar/backend.py", line 253, in update
    self._update_impl(vevent, href, etag)
  File "/usr/lib/python2.7/site-packages/khal/khalendar/backend.py", line 280, in _update_impl
    dtstartend = aux.expand(vevent, self.locale['default_timezone'], href)
  File "/usr/lib/python2.7/site-packages/khal/khalendar/aux.py", line 72, in expand
    rrule._until = rrule._until.astimezone(events_tz)
TypeError: astimezone() argument 1 must be datetime.tzinfo, not None
warning: Skipping study/POORNC0D8YIBMP5J4XGBLVER928SAVTBU4O2.ics: astimezone() argument 1 must be datetime.tzinfo, not None
warning: This event will not be available in khal.
```

Here's the mentioned file:
```
BEGIN:VCALENDAR
PRODID:-//Radicale//NONSGML Radicale Server//EN
VERSION:2.0
BEGIN:VEVENT
LAST-MODIFIED:20150313T112212Z
DTSTAMP:20150313T112212Z
UID:POORNC0D8YIBMP5J4XGBLVER928SAVTBU4O2
SUMMARY:Análisis de Sistemas
RRULE:FREQ=WEEKLY;UNTIL=20150626T220000Z
DTSTART;TZID=local:20150303T190000
DTEND;TZID=local:20150303T220000
SEQUENCE:1
LOCATION:Aula 4-3\, Mario Bravo 1050
X-RADICALE-NAME:POORNC0D8YIBMP5J4XGBLVER928SAVTBU4O2.ics
END:VEVENT
BEGIN:VTIMEZONE
TZID:local
BEGIN:STANDARD
DTSTART;VALUE=DATE-TIME:20090314T230000
TZNAME:ART
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
X-RADICALE-NAME:local
END:STANDARD
X-RADICALE-NAME:local
END:VTIMEZONE
END:VCALENDAR
```

**Comment by mbaldessari** [comment]
Hi @hobarrera ,

I am fairly certain this is issue #159 or #158 
Can you try with git head and report back?

cheers,
Michele

**Comment by hobarrera** [comment]
Yes, I though I was running the latest from git, but I had 0.4.0. Sorry for the noise, this bug was fixed. 😓

Cheers!
