### ISSUE TITLE
%F does not work as longdateformat or dateformat

### ISSUE THREAD

**Issue by hobarrera** [geier/khal#177]
This:

```
[locale]
longdateformat = %F
dateformat = %F
```

Results in an error when saving:

```
Traceback (most recent call last):                                                                                                                                   [26/265]
  File "/usr/lib/python2.7/site-packages/khal-0.5.0.dev_76_g3b5288b_dirty-py2.7.egg/khal/ui/__init__.py", line 844, in start_pane
    loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/site-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python2.7/site-packages/khal-0.5.0.dev_76_g3b5288b_dirty-py2.7.egg/khal/ui/__init__.py", line 771, in keypress
    return super(EventEditor, self).keypress(size, key)
  File "/usr/lib/python2.7/site-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python2.7/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 464, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python2.7/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python2.7/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python2.7/site-packages/khal-0.5.0.dev_76_g3b5288b_dirty-py2.7.egg/khal/ui/__init__.py", line 732, in save
    self.update_vevent()
  File "/usr/lib/python2.7/site-packages/khal-0.5.0.dev_76_g3b5288b_dirty-py2.7.egg/khal/ui/__init__.py", line 709, in update_vevent
    self.event.vevent.add('DTSTART', self.startendeditor.newstart)
  File "/usr/lib/python2.7/site-packages/icalendar/cal.py", line 171, in add
    value = self._encode(name, value, parameters, encode)
  File "/usr/lib/python2.7/site-packages/icalendar/cal.py", line 123, in _encode
    obj = klass(value)
  File "/usr/lib/python2.7/site-packages/icalendar/prop.py", line 276, in __init__
    raise ValueError('You must use datetime, date, timedelta or time')
ValueError: You must use datetime, date, timedelta or time
```
However, this does work:

```
[locale]
longdateformat = %Y-%m-%d
dateformat = %Y-%m-%d
```

According to `man strftime`, they are equivalent:

    %F     Equivalent to %Y-%m-%d (the ISO 8601 date format). (C99)

`man strftime` is suggested by the [documentation](http://khal.readthedocs.org/en/latest/configure.html#locale-timeformat) (as well as https://strftime.net/, which seems to be down).

I suspect that the documentation is wrong, and that we're not using the C implementation of strftime (which `man time` documents), but rather the python implementation, documented [here](https://docs.python.org/2/library/time.html#time.strftime).

**Comment by untitaker** [comment]
Yup, that was a documentation issue. It was probably assumed that Python used the C stdlib under the hood.

**Comment by geier** [comment]
yes, I did actually assume that (and am wondering why it isn't)

**Comment by hobarrera** [comment]
> yes, I did actually assume that (and am wondering why it isn't)

I wonder the same thing actually. Maybe to cope with non-standard implementations?
