### ISSUE TITLE
'str' does not support the buffer interface

### ISSUE THREAD

**Issue by matthiasbeyer** [geier/khal#197]
```
warning: Skipping personal/800a627bf4.ics: 'str' does not support the buffer interface
warning: This event will not be available in khal.
Unknown exception happened.
Traceback (most recent call last):
  File "/nix/store/2g8bi8cnmryx63dsrwnrrgjwhm4dvg1l-python3.4-khal-0.4.0/lib/python3.4/site-packages/khal/khalendar/khalendar.py", line 175, in _update_vevent
    self._dbtool.update(event.raw, href=href, etag=etag)
  File "/nix/store/2g8bi8cnmryx63dsrwnrrgjwhm4dvg1l-python3.4-khal-0.4.0/lib/python3.4/site-packages/khal/khalendar/backend.py", line 253, in update
    self._update_impl(vevent, href, etag)
  File "/nix/store/2g8bi8cnmryx63dsrwnrrgjwhm4dvg1l-python3.4-khal-0.4.0/lib/python3.4/site-packages/khal/khalendar/backend.py", line 280, in _update_impl
    dtstartend = aux.expand(vevent, self.locale['default_timezone'], href)
  File "/nix/store/2g8bi8cnmryx63dsrwnrrgjwhm4dvg1l-python3.4-khal-0.4.0/lib/python3.4/site-packages/khal/khalendar/aux.py", line 62, in expand
    rrule = dateutil.rrule.rrulestr(rrulestr, dtstart=vevent['DTSTART'].dt)
  File "/nix/store/kp28654ln61c2yvvppklb1sxv2dpplvb-python3.4-dateutil-2.2/lib/python3.4/site-packages/dateutil/rrule.py", line 1108, in __call__
    return self._parse_rfc(s, **kwargs)
  File "/nix/store/kp28654ln61c2yvvppklb1sxv2dpplvb-python3.4-dateutil-2.2/lib/python3.4/site-packages/dateutil/rrule.py", line 1025, in _parse_rfc
    (s.find(':') == -1 or s.startswith('RRULE:'))):
TypeError: 'str' does not support the buffer interface
warning: Skipping studying/rem2ics.54ccccb1.242a.3d@localhost.ics: 'str' does not support the buffer interface
warning: This event will not be available in khal.
```

I used vdirsyncer to sync with my owncloud. When calling `khal` a lot of these messages are printed and the displayed calendar remains empty.

I'm on khal version 0.4.0.

If you want to debug this further, I could create an owncloud account on my page for you, if you don't have a own owncloud!

Edit: Ah, btw... I'm on nixos... that's why the pathes in the traceback might look weird to you!

**Comment by hobarrera** [comment]
0.4.0 does not work with python3. Support was added after that release, and you'll need to use the latest version from git.
