### ISSUE TITLE
ikhal crashes when translating event TZs across date boundaries

### ISSUE THREAD

**Issue by plega** [geier/khal#222]
First, congratulations on khal, a great application.

Now, the bug.  I created the following event:

BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/London
BEGIN:DAYLIGHT
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19700329T010000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19701025T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20150701T095323Z
LAST-MODIFIED:20150706T105425Z
DTSTAMP:20150706T105425Z
UID:5507-5593B880-1-15FFE820
SUMMARY:airport transfer :: LHR t5 - home [plega]
ORGANIZER;CN=[...]com
ATTENDEE;PARTSTAT=ACCEPTED;RECEIVED-SEQUENCE=1;ROLE=REQ-PARTICIPANT;RECEIVE
 D-DTSTAMP=20150701T095323Z;CN=plega:mailto:[...]
DTSTART;TZID=Europe/London:20150710T180500
DTEND;TZID=Europe/London:20150710T200000
LOCATION:[...]
CLASS:PUBLIC
TRANSP:OPAQUE
SEQUENCE:1
X-MOZ-GENERATION:1
END:VEVENT
END:VCALENDAR

This displays correctly in ikhal when "local_timezone = Europe/London".  However, if I set "local_timezone = Australia/Sydney" it crashes.  From testing it, I believe (though I haven't tested it exhaustively) that this will happen with any value for local_timezone which results in the above event being split across two days.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/ui/__init__.py", line 653, in start_pane
    loop.run()
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 273, in run
    self.screen.run_wrapper(self._run)
  File "/usr/lib64/python2.7/site-packages/urwid/raw_display.py", line 267, in run_wrapper
    return fn()
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 338, in _run
    self.event_loop.run()
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 668, in run
    self._loop()
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 705, in _loop
    self._watch_files[fd]()
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 389, in _update
    self.process_input(keys)
  File "/usr/lib64/python2.7/site-packages/urwid/main_loop.py", line 489, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib64/python2.7/site-packages/urwid/wimp.py", line 642, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib64/python2.7/site-packages/urwid/container.py", line 1123, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/ui/base.py", line 32, in keypress
    return urwid.Columns.keypress(self, size, key)
  File "/usr/lib64/python2.7/site-packages/urwid/container.py", line 2264, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib64/python2.7/site-packages/urwid/container.py", line 1123, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/ui/calendarwidget.py", line 174, in keypress
    return super(CListBox, self).keypress(size, key)
  File "/usr/lib64/python2.7/site-packages/urwid/listbox.py", line 986, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/ui/calendarwidget.py", line 127, in keypress
    key = super(DateCColumns, self).keypress(size, key)
  File "/usr/lib64/python2.7/site-packages/urwid/container.py", line 2278, in keypress
    self.focus_position = j
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/ui/calendarwidget.py", line 97, in _set_focus_position
    self.on_date_change(self.contents[position][0].original_widget.date)
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/ui/__init__.py", line 629, in show_date
    self.eventscolumn.current_date = date
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/ui/__init__.py", line 221, in current_date
    self.eventcount = self.events.update(date)
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/ui/__init__.py", line 163, in update
    eventcolumn=self.eventcolumn),
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/ui/__init__.py", line 62, in __init__
    super(U_Event, self).__init__(self.event.compact(self.this_date))
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/khalendar/event.py", line 295, in compact
    rstring = self._compact_datetime(day)
  File "/usr/lib/python2.7/site-packages/khal-0.5.0-py2.7.egg/khal/khalendar/event.py", line 333, in _compact_datetime
    'please supply a `day` this event is scheduled on')
ValueError: (u'Something went wrong while displaying "5507-5593B880-1-15FFE820.ics"', u'please supply a `day` this event is scheduled on')

**Comment by geier** [comment]
I think this bug will only appear if the event is scheduled on two different days in the different timezones. I believe this is fixed with the new database layout (see branch `event_rewrite`). I hope to merge that code rather sooner than later.

**Comment by plega** [comment]
I'm looking forward to that.

Meanwhile, I've run some specific tests and here is some more detail, which suggests that the problem isn't exactly as you have described it:

1. If I create an event which falls across midnight in my local TZ, it displays in ikhal on both relevant days.  [That is the desired behaviour.]

2. If I create an event, say, UK BST 14:00-19:00, and then change local TZ to Pacific/Auckland or Pacific/Samoa it will crash.  [Bad]

3. Using the above example, if I set local TZ as Australia/Sydney it displays the event as "23:00-".  If I move to the next day, however, it does *not* display the rest of the event. [Bad]

So it looks as though it is the evaluation of DTSTART which is causing the crash, although incorrect handling of event length is causing the truncation.

**Comment by plega** [comment]
Sorry, didn't mean to close it (!)

**Comment by plega** [comment]
Could we re-open this ?  I get what seems to be the same problem on v0.6.0.

TEST 1: enter event as 14:00-15:00 BST, then change localtime to Aust/Sydney.  Event shows as "23:00-" OK.

TEST 2: event 15:00-17:00 BST, but change localtime to Aust/Sydney and it crashes.

TEST 3: event 15:00-16:00 BST, also crashes.  Sample output (TEST 3):

Traceback (most recent call last):
  File "/usr/bin/ikhal", line 9, in <module>
    load_entry_point('khal==0.6.0', 'console_scripts', 'ikhal')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/khal-0.6.0-py2.7.egg/khal/cli.py", line 315, in interactive_cli
    controllers.interactive(build_collection(ctx), ctx.obj['conf'])
  File "/usr/lib/python2.7/site-packages/khal-0.6.0-py2.7.egg/khal/controllers.py", line 193, in interactive
    description='do something')
  File "/usr/lib/python2.7/site-packages/khal-0.6.0-py2.7.egg/khal/ui/__init__.py", line 596, in __init__
    self.eventscolumn = EventColumn(pane=self)
  File "/usr/lib/python2.7/site-packages/khal-0.6.0-py2.7.egg/khal/ui/__init__.py", line 191, in __init__
    self.events = EventList(eventcolumn=self)
  File "/usr/lib/python2.7/site-packages/khal-0.6.0-py2.7.egg/khal/ui/__init__.py", line 140, in __init__
    self.update()
  File "/usr/lib/python2.7/site-packages/khal-0.6.0-py2.7.egg/khal/ui/__init__.py", line 163, in update
    eventcolumn=self.eventcolumn),
  File "/usr/lib/python2.7/site-packages/khal-0.6.0-py2.7.egg/khal/ui/__init__.py", line 62, in __init__
    super(U_Event, self).__init__(self.event.compact(self.this_date))
  File "/usr/lib/python2.7/site-packages/khal-0.6.0-py2.7.egg/khal/khalendar/event.py", line 295, in compact
    rstring = self._compact_datetime(day)
  File "/usr/lib/python2.7/site-packages/khal-0.6.0-py2.7.egg/khal/khalendar/event.py", line 333, in _compact_datetime
    'please supply a `day` this event is scheduled on')
ValueError: (u'Something went wrong while displaying "KBBZP5B2TIEYZQOTF8DX87WJ3T6L4WI8B63W.ics"', u'please supply a `day` this event is scheduled on')

**Comment by geier** [comment]
Sure, I'll have a look tomorrow

**Comment by geier** [comment]
It looks like you are using khal v.0.6 now, right? This version does not yet contain the fix for the above probvem. Please test with the latest version from git (either by downloading from git (`git clone https://github.com/geier/khal.git khal`) or by downloading and than creating a file `version.py` by hand, see #230).

**Comment by plega** [comment]
Now running khal, version 0.6.1.dev52+ng57fa447

It looks good - I can't break it. ;-)
You can close this bug.

Thanks

Philip


On Tue, Jul 21, 2015 at 12:49:17PM +0100, Christian Geier wrote:
> It looks like you are using khal v.0.6 now, right? This version does not yet contain the fix for the above probvem. Please test with the latest version from git (either by downloading from git (`git clone https://github.com/geier/khal.git khal`) or by downloading and than creating a file `version.py` by hand, see #230).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/geier/khal/issues/222#issuecomment-123278950

-- 
Philip Allen, Executive Chairman, CoreFiling Limited
http://www.corefiling.com
Phone: +44-1865-203192  Mobile: +44-7956-160959

**Comment by geier** [comment]
alright and thanks for reporting this.
