### ISSUE TITLE
 support for RDATE, EXDATE, RRULE:UNTIL with invalid timezone information

### ISSUE THREAD

**Issue by geier** [geier/khal#228]

**Comment by madduck** [comment]
Maybe related, I have an event here with the following contents:

> DTSTART;TZID=Europe/Berlin:20140526T090000
> DTEND;TZID=Europe/Berlin:20140526T120000
> RRULE:FREQ=WEEKLY;UNTIL=20140814T215959Z;BYDAY=MO,WE
> EXDATE;TZID=Europe/Berlin:20140827T090000

and this causes a throwback upon launch of khal or ikhal:

    Unknown exception happened.
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/khal/khalendar/khalendar.py", line 286, in _update_vevent
      	update(event.raw, href=href, etag=etag, calendar=calendar)
      File "/usr/lib/python3/dist-packages/khal/khalendar/backend.py", line 260, in update
      	self._update_impl(vevent, href, calendar)
      File "/usr/lib/python3/dist-packages/khal/khalendar/backend.py", line 349, in _update_impl
      	dtstartend = aux.expand(vevent, href)
      File "/usr/lib/python3/dist-packages/khal/khalendar/aux.py", line 106, in expand
      	dtstartl.remove(date)
    KeyError: datetime.datetime(2014, 8, 27, 9, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>)
    warning: Skipping pennycal/4EC1BC2F-75AE-4F10-9B86-D5C41C375308.ics: datetime.datetime(2014, 8, 27, 9, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>)
    warning: This event will not be available in khal.

To me, the timezone looks alright and seems to be parsed just fine, but maybe
the `EXDATE` can't be processed? If I manually remove the line, then it works.

**Comment by geier** [comment]
No, this is a different problem: the excluded date is *after* the end date of this sequence. We should probably throw a warning and not raise an exception.

**Comment by madduck** [comment]
Hah, you have very sharp eyes. I totally missed this. Thanks!
