### ISSUE TITLE
Search crashes if TZ is incorrect

### ISSUE THREAD

**Issue by plega** [geier/khal#240]
Search crashes if the resultant record contains incomplete TZ info, such as is often the case with records originating from Micrsoft.

PASS CASE - search returns this record correctly

BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
DESCRIPTION:XYZZY
DTEND:20150630T160000Z
DTSTART;TZID=Europe/London:20150630T150000
UID:12345687
END:VEVENT
END:VCALENDAR

FAIL CASE - search crashes on this record

BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
DESCRIPTION:XYZZY
DTEND:20150630T160000Z
DTSTART:20150630T150000Z
UID:12345687
END:VEVENT
END:VCALENDAR

ERROR MESSAGE - what the fail case produces

plega@serpentine khal$ khal search -a test XYZZY
Traceback (most recent call last):
  File "/usr/bin/khal", line 9, in <module>
    load_entry_point('khal==0.6.1.dev52+ng57fa447', 'console_scripts', 'khal')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/khal-0.6.1.dev52+ng57fa447-py2.7.egg/khal/cli.py", line 356, in search
    desc = textwrap.wrap(event.event_description, term_width)
  File "/usr/lib/python2.7/site-packages/khal-0.6.1.dev52+ng57fa447-py2.7.egg/khal/khalendar/event.py", line 394, in event_description
    self._rangestr, self.summary, location, repitition, description)
  File "/usr/lib/python2.7/site-packages/khal-0.6.1.dev52+ng57fa447-py2.7.egg/khal/khalendar/event.py", line 401, in _rangestr
    if self.start_local.utctimetuple()[:3] == self.end_local.utctimetuple()[:3]:
  File "/usr/lib/python2.7/site-packages/khal-0.6.1.dev52+ng57fa447-py2.7.egg/khal/khalendar/event.py", line 453, in start_local
    return self._locale['local_timezone'].localize(self.start)
  File "/usr/lib/python2.7/site-packages/pytz/tzinfo.py", line 304, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)

**Comment by geier** [comment]
Thank you for reporting this, please reopen if it isn't fixed.

**Comment by plega** [comment]
Confirmed - bug fixed in 0.6.1.dev63+ng833a7a5
