### ISSUE TITLE
ikhal delete not working

### ISSUE THREAD

**Issue by coachshea** [geier/khal#248]
When running ikhal and I select an item and type 'd', the item is marked for deletion as expected, but when I close ikhal, I get the following error:

Traceback (most recent call last):
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/khal/ui/__init__.py", line 653, in start_pane
    loop.run()
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/urwid/main_loop.py", line 272, in run
    self.screen.run_wrapper(self._run)
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/urwid/raw_display.py", line 242, in run_wrapper
    return fn()
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/urwid/main_loop.py", line 337, in _run
    self.event_loop.run()
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/urwid/main_loop.py", line 708, in run
    self._loop()
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/urwid/main_loop.py", line 787, in _loop
    self._watch_files[fd]()
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/urwid/main_loop.py", line 388, in _update
    self.process_input(keys)
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/urwid/main_loop.py", line 494, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/urwid/main_loop.py", line 540, in unhandled_input
    return self._unhandled_input(input)
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/khal/ui/base.py", line 203, in on_key_press
    self.backtrack()
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/khal/ui/base.py", line 193, in backtrack
    cb(data)
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/khal/ui/__init__.py", line 637, in cleanup
    self.collection.delete(href, etag, account)
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/khal/khalendar/khalendar.py", line 333, in delete
    self._calnames[calendar].delete(href, etag)
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/khal/khalendar/khalendar.py", line 198, in delete
    self._storage.delete(href, etag)
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/vdirsyncer/storage/base.py", line 17, in inner
    return f(self, *args, **kwargs)
  File "/home/coachshea/.virtualenvs/khal/lib/python3.4/site-packages/vdirsyncer/storage/filesystem.py", line 171, in delete
    raise exceptions.WrongEtagError(etag, actual_etag)
vdirsyncer.exceptions.WrongEtagError: ('1438977400.160679817', '1439385694311919872.000000000')

This seems to happen every time whether I try to delete one or multiple events. urwid is up to date. Any ideas?

**Comment by geier** [comment]
It looks like between starting up ikhal and quitting the event has been changed. But the access time (etag) looks invalid (`actual_etag` is pretty far into the future).
@untitaker do you have an idea who that `actual_etag` can come about?

**Comment by coachshea** [comment]
I don't but I have discovered that this doesn't apply to new appointments that I create now. I can delete them, change them, and everything works as expected only the old ones are doing this.

**Comment by geier** [comment]
I believe I found the bug. Did you have another event with the same filename, but in another calendar?
