### ISSUE TITLE
Invalid iCalendar duration: -PT0DT0H10M0S

### ISSUE THREAD

**Issue by fpytloun** [geier/khal#290]
Hello,
I am receiving this error for one of my events:

```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/khal/khalendar/khalendar.py", line 233, in _update_vevent
    self._dbtool.update(event.raw, href=href, etag=etag)
  File "/usr/local/lib/python2.7/dist-packages/khal/khalendar/backend.py", line 242, in update
    ical = icalendar.Event.from_ical(vevent_str)
  File "/usr/lib/python2.7/dist-packages/icalendar/cal.py", line 350, in from_ical
    vals = factory(factory.from_ical(vals))
  File "/usr/lib/python2.7/dist-packages/icalendar/prop.py", line 314, in from_ical
    return vDuration.from_ical(ical)
  File "/usr/lib/python2.7/dist-packages/icalendar/prop.py", line 465, in from_ical
    raise ValueError('Invalid iCalendar duration: %s' % ical)
ValueError: Invalid iCalendar duration: -PT0DT0H10M0S
warning: Skipping personal/daf246e1c34a4f9ba8e9c3f86546d0c5.ics: Invalid iCalendar duration: -PT0DT0H10M0S
warning: This event will not be available in khal.
```

ics file downloaded with vdirsyncer looks like this:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 1.1.1
BEGIN:VEVENT
DTSTART;VALUE=DATE:20151025
DTEND;VALUE=DATE:20151108
DTSTAMP:20151016T144631Z
CREATED:20150831T205706Z
DESCRIPTION:Odlet 10:20\, přílet do Prahy 21:05
LAST-MODIFIED:20151016T144631Z
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:Japonsko
TRANSP:TRANSPARENT
CLASS:PUBLIC
UID:daf246e1c34a4f9ba8e9c3f86546d0c5
CATEGORIES:
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:owncloud
TRIGGER:-PT0DT0H10M0S
END:VALARM
END:VEVENT
END:VCALENDAR
```

Is something wrong with `TRIGGER:-PT0DT0H10M0S`? Maybe this could be a bug in calendarplus owncloud app.

Khal version:
`khal, version v0.6.1.dev135+ngc31866e`

**Comment by geier** [comment]
Hi,
you're right, it looks like that DURATION is invalid, i.e., the first
`T` does not belong there (see
https://tools.ietf.org/html/rfc5545#section-3.3.6) and therefore
icalendar fails to parse it. You can manually fix this (by removing
that), but you might want to log this bug with the owncloud team as
well.

Quoting Filip Pytloun (2015-10-23 14:35:13)

**Comment by fpytloun** [comment]
Thank you for clarification. Fixed duration manually and it's working fine again :-)
I will try to reproduce the issue and report to owncloud.
