### ISSUE TITLE
ikhal: UnicodeDecodeError

### ISSUE THREAD

**Issue by dzoep** [geier/khal#293]
Another round of closed issue #142 

I'd like to reopen this - even with latest sources I get:

Traceback (most recent call last):
File "", line 1, in
File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in call
return self.main(args, *kwargs)
File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
rv = self.invoke(ctx)
File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
return ctx.invoke(self.callback, *ctx.params)
File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
return callback(args, *kwargs)
File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/decorators.py", line 16, in new_func
return f(get_current_context(), *args, *kwargs)
File "./khal/cli.py", line 359, in interactive_cli
controllers.interactive(build_collection(ctx), ctx.obj['conf'])
File "./khal/controllers.py", line 211, in interactive
description='do something')
File "./khal/ui/init.py", line 624, in init
get_styles=collection.get_styles
File "./khal/ui/calendarwidget.py", line 522, in init
weekheader = weekheader.decode('utf-8')
File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 13: invalid continuation byte

My locale is cs_CZ.UTF-8 and if I add "print weekheader" to line 520 (just after weekheader = calendar.weekheader(2), I get following (ran through hexdump -C to see the problem):

00000000 50 6f 20 c3 9a 20 53 74 20 c4 8c 20 50 c3 20 53 |Po .. St .. P. S|
00000010 6f 20 4e 65 0a |o Ne.|
00000015

Monday = "Po" ... ok
Tuesday = "Út" => "Ú" ... not OK, but doesn't fail (two bytes, not two unicode characters)
...
Friday = "Pá" => "P?" (50 c3) ... not OK and causes the exception seen above.

After a few experiments with calendar.weekheader I think it is broken in the python2 series:

Python 2.7.10 (default, Sep 28 2015, 16:33:16) 
[GCC 4.8.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> import calendar
>>> locale.setlocale(locale.LC_ALL,"cs_CZ.UTF-8")
'cs_CZ.UTF-8'
>>> calendar.weekheader(2)
'Po \xc3\x9a St \xc4\x8c P\xc3 So Ne'

I also noticed that khal doesn't use the locale properly so in "C" locale it is all ok - so probably khal has the same problem as ikhal if it would use my UTF-8 locale.

**Comment by geier** [comment]
grr, I really thought I had this fixed. Just to make sure I'm getting right what's broken:
  * python 2, 3 or both?
  * khal, ikhal or both?

Also, does khal currently not display localized weekheaders?

**Comment by dzoep** [comment]
The test case works with python3 so I assume python3 is ok.

I am using khal/ikhal with python2 so that definitely is broken.

ikhal - yup, throws aforementioned exception with cs_CZ.UTF-8 locales

khal - dunno, does NOT display localized weekeaders

**Comment by geier** [comment]
ok, I found the issue, ``calendar.formatweekheader(n)`` just cuts off after *n bytes*, not characters. There is calendar.LocaleTextCalendar().formatweekehader though (which one needs to tell the locale though...). I'll try to have a fix later this evening.

**Comment by geier** [comment]
@dzoep could you give branch [https://github.com/geier/khal/tree/weekheaders](weekheaders) a try?

**Comment by dzoep** [comment]
@geier ikhal from weekheaders branch work, khal gives following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 1007, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./khal/cli.py", line 226, in cli
    ctx.invoke(cli.commands[command])
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click-5.1-py2.7.egg/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./khal/cli.py", line 254, in calendar
    full=full
  File "./khal/controllers.py", line 160, in calendar
    locale=locale)
  File "./khal/calendar_display.py", line 181, in vertical_month
    mylocale = '.'.join(getlocale())
TypeError: sequence item 0: expected string, NoneType found

**Comment by geier** [comment]
turns out, I really don't understand how the locale module in python works (i.e. why getlocale() returns None, None in khal but the proper locale in ikhal)

**Comment by geier** [comment]
@dzoep could you test again?

**Comment by dzoep** [comment]
@geier awesome, both now works and display correctly abbreviated localized headers ... until you try with C locale (I tried LC_ALL=C) - then both fail with the same exception (None ...)

**Comment by geier** [comment]
I believe I fixed this now, if you (or anyone else) finds that this error is in fact not fixed, please reopen this or create a new issue.

Thank you @dzoep for reporting and testing this!
