### ISSUE TITLE
delete_instance doesn't work

### ISSUE THREAD

**Issue by Eisfreak7** [geier/khal#299]
Hi
I wanted to be able to delete single instances, so I updated my khal from 0.6 to the latest development version.
Trying to delete an instance of a recurring event now, the correct dialog is displayed.
When I select 'only this' though, `ikhal  -v` crashes with the following error (and without deleting anything):
```
debug: using the config file at /home/eisfreak7/.config/khal/khal.conf
debug: khal 0.6.1.dev205+ngc8a11b0.d20151117
debug: Using config:
debug: [calendars]
debug:   [[cal1]]
debug:     path: /home/timo/data/calendars/cal1.ics/
debug:     color: dark blue
debug:     readonly: False
debug:     type: calendar
debug:   [[cal2]]
debug:     path: /home/timo/data/calendars/cal2.ics/
debug:     color: light blue
debug:     readonly: False
debug:     type: calendar
debug:   [[cal3]]
debug:     path: /home/timo/data/calendars/cal3.ics/
debug:     color: dark magenta
debug:     readonly: False
debug:     type: calendar
debug:   [[cal4]]
debug:     path: /home/timo/data/calendars/cal4.ics/
debug:     color: dark cyan
debug:     readonly: False
debug:     type: calendar
debug: [locale]
debug:   longdateformat: %Y-%m-%d
debug:   longdatetimeformat: %Y-%m-%d %H:%M
debug:   datetimeformat: %y-%m-%d %H:%M
debug:   timeformat: %H:%M
debug:   dateformat: %y-%m-%d
debug:   encoding: utf-8
debug:   firstweekday: 0
debug:   unicode_symbols: True
debug:   default_timezone: Europe/Berlin
debug:   local_timezone: Europe/Berlin
debug:   weeknumbers: False
debug: [default]
debug:   default_command: agenda
debug:   print_new: event
debug:   days: 2
debug:   default_calendar: None
debug:   show_all_days: False
debug:   highlight_event_days: False
debug: [sqlite]
debug:   path: /home/eisfreak7/.local/share/khal/khal.db
debug: [keybindings]
debug:   up: ['up', 'k']
debug:   down: ['down', 'j']
debug:   right: ['right', 'l', ' ']
debug:   left: ['left', 'h', 'backspace']
debug:   new: ['n']
debug:   delete: ['d']
debug:   view: ['enter', 'tab']
debug:   today: ['t']
debug:   save: ['meta enter']
debug:   duplicate: ['p']
debug: [view]
debug:   event_view_weighting: 1
debug:   event_view_always_visible: False
debug:   theme: dark
debug:   frame: False
debug: [highlight_days]
debug:   method: fg
debug:   color: 
debug:   multiple: 
debug:   default_color: 
debug: created version table
debug: tables for calendar cal1 exist
debug: created version table
debug: tables for calendar cal2 exist
debug: created version table
debug: tables for calendar cal3 exist
debug: created version table
debug: tables for calendar cal4 exist
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 675, in start_pane
    loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 715, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 592, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3.5/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 91, in delete_this
    self.event.delete_instance(instance)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/event.py", line 422, in delete_instance
    delete_instance(self._vevents['PROTO'], instance)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/aux.py", line 279, in delete_instance
    _add_exdate(vevent, instance)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/aux.py", line 237, in _add_exdate
    vevent.add('EXDATE', instance)
  File "/usr/lib/python3.5/site-packages/icalendar/cal.py", line 174, in add
    value = self._encode(name, value, parameters, encode)
  File "/usr/lib/python3.5/site-packages/icalendar/cal.py", line 126, in _encode
    obj = klass(value)
  File "/usr/lib/python3.5/site-packages/icalendar/prop.py", line 247, in __init__
    dt = vDDDTypes(dt)
  File "/usr/lib/python3.5/site-packages/icalendar/prop.py", line 277, in __init__
    raise ValueError('You must use datetime, date, timedelta or time')
ValueError: You must use datetime, date, timedelta or time
```
I'm using Arch with the khal-git AUR-Package.

**Comment by geier** [comment]
Could you paste the event you are trying to delete (as with my recurring events I cannot reproduce this error)?

**Comment by Eisfreak7** [comment]
Oh, you're right. It doesn't happen with every event.
I actually have 2 files with  the same event name, and I'm not sure which one is the correct one as I don't understand the ics format. So I'll post them both. The failing task occurs at 2015-11-17, 14:15-15:45
```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Vorlesungen
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VEVENT
DTSTAMP:20151118T132142Z
UID:2maplgauq0v30tqs8af5t9la58@google.com
RECURRENCE-ID:20151021T121500Z
SEQUENCE:2
DTSTART;TZID=Europe/Berlin:20151021T141500
DTEND;TZID=Europe/Berlin:20151021T154500
SUMMARY:GP1 Vorlesung
LOCATION:L1
DESCRIPTION:Prof. Dr. Stefan Böttcher
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT120M
ACTION:DISPLAY
DESCRIPTION:GP1 Vorlesung
X-RADICALE-NAME:2maplgauq0v30tqs8af5t9la58@google.com
END:VALARM
X-RADICALE-NAME:2maplgauq0v30tqs8af5t9la58@google.com
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20151118T132142Z
UID:2maplgauq0v30tqs8af5t9la58@google.com
RECURRENCE-ID:20151118T131500Z
SEQUENCE:3
DTSTART;TZID=Europe/Berlin:20151118T141500
DTEND;TZID=Europe/Berlin:20151118T154500
SUMMARY:GP1 Vorlesung
LOCATION:L1
DESCRIPTION:Prof. Dr. Stefan Böttcher
STATUS:CANCELLED
BEGIN:VALARM
TRIGGER:-PT30M
ACTION:DISPLAY
DESCRIPTION:GP1 Vorlesung
X-RADICALE-NAME:2maplgauq0v30tqs8af5t9la58@google.com
END:VALARM
X-RADICALE-NAME:2maplgauq0v30tqs8af5t9la58@google.com
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20151118T132142Z
UID:2maplgauq0v30tqs8af5t9la58@google.com
SEQUENCE:2
DTSTART;TZID=Europe/Berlin:20151021T141500
DURATION:PT1H30M
RRULE:FREQ=WEEKLY;UNTIL=20160210T131500Z;BYDAY=WE
SUMMARY:GP1 Vorlesung
LOCATION:L1
DESCRIPTION:Prof. Dr. Stefan Böttcher
STATUS:CONFIRMED
X-RADICALE-NAME:2maplgauq0v30tqs8af5t9la58@google.com
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
X-RADICALE-NAME:Europe/Berlin
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
X-RADICALE-NAME:Europe/Berlin
END:STANDARD
X-RADICALE-NAME:Europe/Berlin
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Europe/London
TZURL:http://tzurl.org/zoneinfo/Europe/London
X-LIC-LOCATION:Europe/London
BEGIN:DAYLIGHT
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19810329T010000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
X-RADICALE-NAME:Europe/London
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19961027T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
X-RADICALE-NAME:Europe/London
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-000115
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:18471201T000000
RDATE:18471201T000000
X-RADICALE-NAME:Europe/London
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19160521T020000
RDATE:19160521T020000
RDATE:19170408T020000
RDATE:19180324T020000
RDATE:19190330T020000
RDATE:19200328T020000
RDATE:19210403T020000
RDATE:19220326T020000
RDATE:19230422T020000
RDATE:19240413T020000
RDATE:19250419T020000
RDATE:19260418T020000
RDATE:19270410T020000
RDATE:19280422T020000
RDATE:19290421T020000
RDATE:19300413T020000
RDATE:19310419T020000
RDATE:19320417T020000
RDATE:19330409T020000
RDATE:19340422T020000
RDATE:19350414T020000
RDATE:19360419T020000
RDATE:19370418T020000
RDATE:19380410T020000
RDATE:19390416T020000
RDATE:19400225T020000
RDATE:19460414T030000
RDATE:19470316T020000
RDATE:19480314T020000
RDATE:19490403T020000
RDATE:19500416T020000
RDATE:19510415T020000
RDATE:19520420T020000
RDATE:19530419T020000
RDATE:19540411T020000
RDATE:19550417T020000
RDATE:19560422T020000
RDATE:19570414T020000
RDATE:19580420T020000
RDATE:19590419T020000
RDATE:19600410T020000
RDATE:19610326T020000
RDATE:19620325T020000
RDATE:19630331T020000
RDATE:19640322T020000
RDATE:19650321T020000
RDATE:19660320T020000
RDATE:19670319T020000
RDATE:19680218T020000
RDATE:19720319T020000
RDATE:19730318T020000
RDATE:19740317T020000
RDATE:19750316T020000
RDATE:19760321T020000
RDATE:19770320T020000
RDATE:19780319T020000
RDATE:19790318T020000
RDATE:19800316T020000
X-RADICALE-NAME:Europe/London
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19161001T030000
RDATE:19161001T030000
RDATE:19170917T030000
RDATE:19180930T030000
RDATE:19190929T030000
RDATE:19201025T030000
RDATE:19211003T030000
RDATE:19221008T030000
RDATE:19230916T030000
RDATE:19240921T030000
RDATE:19251004T030000
RDATE:19261003T030000
RDATE:19271002T030000
RDATE:19281007T030000
RDATE:19291006T030000
RDATE:19301005T030000
RDATE:19311004T030000
RDATE:19321002T030000
RDATE:19331008T030000
RDATE:19341007T030000
RDATE:19351006T030000
RDATE:19361004T030000
RDATE:19371003T030000
RDATE:19381002T030000
RDATE:19391119T030000
RDATE:19451007T030000
RDATE:19461006T030000
RDATE:19471102T030000
RDATE:19481031T030000
RDATE:19491030T030000
RDATE:19501022T030000
RDATE:19511021T030000
RDATE:19521026T030000
RDATE:19531004T030000
RDATE:19541003T030000
RDATE:19551002T030000
RDATE:19561007T030000
RDATE:19571006T030000
RDATE:19581005T030000
RDATE:19591004T030000
RDATE:19601002T030000
RDATE:19611029T030000
RDATE:19621028T030000
RDATE:19631027T030000
RDATE:19641025T030000
RDATE:19651024T030000
RDATE:19661023T030000
RDATE:19671029T030000
RDATE:19711031T030000
RDATE:19721029T030000
RDATE:19731028T030000
RDATE:19741027T030000
RDATE:19751026T030000
RDATE:19761024T030000
RDATE:19771023T030000
RDATE:19781029T030000
RDATE:19791028T030000
RDATE:19801026T030000
RDATE:19811025T020000
RDATE:19821024T020000
RDATE:19831023T020000
RDATE:19841028T020000
RDATE:19851027T020000
RDATE:19861026T020000
RDATE:19871025T020000
RDATE:19881023T020000
RDATE:19891029T020000
RDATE:19901028T020000
RDATE:19911027T020000
RDATE:19921025T020000
RDATE:19931024T020000
RDATE:19941023T020000
RDATE:19951022T020000
X-RADICALE-NAME:Europe/London
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:BDST
DTSTART:19410504T020000
RDATE:19410504T020000
RDATE:19420405T020000
RDATE:19430404T020000
RDATE:19440402T020000
RDATE:19450402T030000
RDATE:19470413T020000
X-RADICALE-NAME:Europe/London
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19410810T030000
RDATE:19410810T030000
RDATE:19420809T030000
RDATE:19430815T030000
RDATE:19440917T030000
RDATE:19450715T020000
RDATE:19470810T030000
X-RADICALE-NAME:Europe/London
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19681027T000000
RDATE:19681027T000000
X-RADICALE-NAME:Europe/London
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19960101T000000
RDATE:19960101T000000
X-RADICALE-NAME:Europe/London
END:STANDARD
X-RADICALE-NAME:Europe/London
END:VTIMEZONE
END:VCALENDAR
```
```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Vorlesungen
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
X-RADICALE-NAME:Europe/Berlin
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
X-RADICALE-NAME:Europe/Berlin
END:STANDARD
X-RADICALE-NAME:Europe/Berlin
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Europe/London
TZURL:http://tzurl.org/zoneinfo/Europe/London
X-LIC-LOCATION:Europe/London
BEGIN:DAYLIGHT
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19810329T010000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
X-RADICALE-NAME:Europe/London
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19961027T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
X-RADICALE-NAME:Europe/London
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-000115
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:18471201T000000
RDATE:18471201T000000
X-RADICALE-NAME:Europe/London
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19160521T020000
RDATE:19160521T020000
RDATE:19170408T020000
RDATE:19180324T020000
RDATE:19190330T020000
RDATE:19200328T020000
RDATE:19210403T020000
RDATE:19220326T020000
RDATE:19230422T020000
RDATE:19240413T020000
RDATE:19250419T020000
RDATE:19260418T020000
RDATE:19270410T020000
RDATE:19280422T020000
RDATE:19290421T020000
RDATE:19300413T020000
RDATE:19310419T020000
RDATE:19320417T020000
RDATE:19330409T020000
RDATE:19340422T020000
RDATE:19350414T020000
RDATE:19360419T020000
RDATE:19370418T020000
RDATE:19380410T020000
RDATE:19390416T020000
RDATE:19400225T020000
RDATE:19460414T030000
RDATE:19470316T020000
RDATE:19480314T020000
RDATE:19490403T020000
RDATE:19500416T020000
RDATE:19510415T020000
RDATE:19520420T020000
RDATE:19530419T020000
RDATE:19540411T020000
RDATE:19550417T020000
RDATE:19560422T020000
RDATE:19570414T020000
RDATE:19580420T020000
RDATE:19590419T020000
RDATE:19600410T020000
RDATE:19610326T020000
RDATE:19620325T020000
RDATE:19630331T020000
RDATE:19640322T020000
RDATE:19650321T020000
RDATE:19660320T020000
RDATE:19670319T020000
RDATE:19680218T020000
RDATE:19720319T020000
RDATE:19730318T020000
RDATE:19740317T020000
RDATE:19750316T020000
RDATE:19760321T020000
RDATE:19770320T020000
RDATE:19780319T020000
RDATE:19790318T020000
RDATE:19800316T020000
X-RADICALE-NAME:Europe/London
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19161001T030000
RDATE:19161001T030000
RDATE:19170917T030000
RDATE:19180930T030000
RDATE:19190929T030000
RDATE:19201025T030000
RDATE:19211003T030000
RDATE:19221008T030000
RDATE:19230916T030000
RDATE:19240921T030000
RDATE:19251004T030000
RDATE:19261003T030000
RDATE:19271002T030000
RDATE:19281007T030000
RDATE:19291006T030000
RDATE:19301005T030000
RDATE:19311004T030000
RDATE:19321002T030000
RDATE:19331008T030000
RDATE:19341007T030000
RDATE:19351006T030000
RDATE:19361004T030000
RDATE:19371003T030000
RDATE:19381002T030000
RDATE:19391119T030000
RDATE:19451007T030000
RDATE:19461006T030000
RDATE:19471102T030000
RDATE:19481031T030000
RDATE:19491030T030000
RDATE:19501022T030000
RDATE:19511021T030000
RDATE:19521026T030000
RDATE:19531004T030000
RDATE:19541003T030000
RDATE:19551002T030000
RDATE:19561007T030000
RDATE:19571006T030000
RDATE:19581005T030000
RDATE:19591004T030000
RDATE:19601002T030000
RDATE:19611029T030000
RDATE:19621028T030000
RDATE:19631027T030000
RDATE:19641025T030000
RDATE:19651024T030000
RDATE:19661023T030000
RDATE:19671029T030000
RDATE:19711031T030000
RDATE:19721029T030000
RDATE:19731028T030000
RDATE:19741027T030000
RDATE:19751026T030000
RDATE:19761024T030000
RDATE:19771023T030000
RDATE:19781029T030000
RDATE:19791028T030000
RDATE:19801026T030000
RDATE:19811025T020000
RDATE:19821024T020000
RDATE:19831023T020000
RDATE:19841028T020000
RDATE:19851027T020000
RDATE:19861026T020000
RDATE:19871025T020000
RDATE:19881023T020000
RDATE:19891029T020000
RDATE:19901028T020000
RDATE:19911027T020000
RDATE:19921025T020000
RDATE:19931024T020000
RDATE:19941023T020000
RDATE:19951022T020000
X-RADICALE-NAME:Europe/London
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:BDST
DTSTART:19410504T020000
RDATE:19410504T020000
RDATE:19420405T020000
RDATE:19430404T020000
RDATE:19440402T020000
RDATE:19450402T030000
RDATE:19470413T020000
X-RADICALE-NAME:Europe/London
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19410810T030000
RDATE:19410810T030000
RDATE:19420809T030000
RDATE:19430815T030000
RDATE:19440917T030000
RDATE:19450715T020000
RDATE:19470810T030000
X-RADICALE-NAME:Europe/London
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19681027T000000
RDATE:19681027T000000
X-RADICALE-NAME:Europe/London
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19960101T000000
RDATE:19960101T000000
X-RADICALE-NAME:Europe/London
END:STANDARD
X-RADICALE-NAME:Europe/London
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20151117T110508Z
UID:ngjkb9jocir9fbsb1ccnbiikrs@google.com
RECURRENCE-ID:20151117T131500Z
SEQUENCE:1
DTSTART;TZID=Europe/Berlin:20151117T141500
DTEND;TZID=Europe/Berlin:20151117T154500
SUMMARY:GP1 Vorlesung
STATUS:CANCELLED
X-RADICALE-NAME:ngjkb9jocir9fbsb1ccnbiikrs@google.com
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20151117T110508Z
UID:ngjkb9jocir9fbsb1ccnbiikrs@google.com
SEQUENCE:1
DTSTART;TZID=Europe/Berlin:20151020T141500
DURATION:PT1H30M
RRULE:FREQ=WEEKLY;UNTIL=20160209T131500Z;BYDAY=TU
SUMMARY:GP1 Vorlesung
LOCATION:L1
DESCRIPTION:Prof. Dr. Stefan Böttcher
STATUS:CONFIRMED
X-RADICALE-NAME:ngjkb9jocir9fbsb1ccnbiikrs@google.com
END:VEVENT
END:VCALENDAR
```

**Comment by Eisfreak7** [comment]
For some reason I had to reinstall khal (after the normal update via the aur it didn't work), but now everything works wonderfully.
Thank you for your effort and this tool, I really enjoy using it :)

**Comment by geier** [comment]
You're welcome! I have no idea about the arch issue though.
