### ISSUE TITLE
khal at broken in master

### ISSUE THREAD

**Issue by languitar** [geier/khal#313]
```
~/local/trusty/x86_64/src/khal (master) [1]> khal at '13.12.2015'
Traceback (most recent call last):
  File "/homes/jwienke/local/all/bin/khal", line 9, in <module>
    load_entry_point('khal==v0.7.1.dev35-ng33c5373', 'console_scripts', 'khal')()
  File "/homes/jwienke/local/all/opt/khal/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/homes/jwienke/local/all/opt/khal/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/homes/jwienke/local/all/opt/khal/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/homes/jwienke/local/all/opt/khal/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/homes/jwienke/local/all/opt/khal/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/homes/jwienke/local/all/opt/khal/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/homes/jwienke/local/all/opt/khal/lib/python3.4/site-packages/khal-v0.7.1.dev35_ng33c5373-py3.4.egg/khal/cli.py", line 450, in at
    ctx.obj['conf']['locale']['encoding']
  File "/homes/jwienke/local/all/opt/khal/lib/python3.4/site-packages/click/utils.py", line 259, in echo
    file.write(message)
AttributeError: 'str' object has no attribute 'write'
```

**Comment by geier** [comment]
Thank you for reporting this! I believe I just fixed it, please reopen if it isn't doesn't work for you.

**Comment by languitar** [comment]
Yes, works now.

**Comment by geier** [comment]
I really need to increase the test coverage, this should have been caught.
