### ISSUE TITLE
Ctrl+w crashes khal

### ISSUE THREAD

**Issue by hobarrera** [geier/khal#327]
0.7.1.dev74+ng6e92587-1

I hit ctrl+w while the location field was focused, and ikhal crashed:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 846, in start_pane
    loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 631, in keypress
    return super(EventEditor, self).keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.5/site-packages/khal/ui/widgets.py", line 72, in keypress
    self._delete_word()
  File "/usr/lib/python3.5/site-packages/khal/ui/widgets.py", line 86, in _delete_word
    text = self.get_edit_text().decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

Versions of all of khal's dependencies:

```
$ pacman -Q $(pactree  khal | grep -o "python.*" | sort | uniq)
python 3.5.1-1
python-atomicwrites 0.1.8-3
python-chardet 2.3.0-2
python-click 6.2-1
python-click-log 0.1.3-1
python-click-threading 0.1.2-1
python-configobj 5.0.6-2
python-dateutil 2.4.2-2
python-icalendar 3.9.1-2
python-lxml 3.5.0-1
python-packaging 15.3-2
python-pkginfo 1.2.1-3
python-pytz 2015.7-1
python-requests 2.9.1-1
python-requests-toolbelt 0.5.1-1
python-setuptools 1:19.4-1
python-six 1.10.0-1
python-tzlocal 1.2-2
python-urllib3 1.14-1
python-urwid 1.3.1-2
python-xdg 0.25-3
```

**Comment by geier** [comment]
Thanks! I believe I just fixed this, if not, please reopen.

**Comment by hobarrera** [comment]
Yes, it's been fixed. Thanks!

**Comment by geier** [comment]
I'm really wondering if this worked at all in python 3 before.
