### ISSUE TITLE
`highlight_event_days` requires `color` to be set

### ISSUE THREAD

**Issue by lucc** [geier/khal#334]
If I set `highlight_event_days=True` I also need to set a `color` in the `[calendar]` sections. Otherwise I get an exception.

config: save this file as `test.conf`
```
[default]
  default_calendar = test
  highlight_event_days = True
[calendars]
  [[test]]
    path = ~/.local/share/khal/calendars/test
    #color = dark red
```
setup: run `khal -c test.conf new tomorrow foobar` in the shell to create an event.

error: run `khal -c test.conf` to see this stack trace:
```
Traceback (most recent call last):
  File "/usr/bin/khal", line 9, in <module>
    load_entry_point('khal==0.7.0', 'console_scripts', 'khal')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/khal/cli.py", line 226, in cli
    ctx.invoke(cli.commands[command])
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/khal/cli.py", line 254, in calendar
    full=full
  File "/usr/lib/python3.5/site-packages/khal/controllers.py", line 158, in calendar
    locale=locale)
  File "/usr/lib/python3.5/site-packages/khal/calendar_display.py", line 195, in vertical_month
    multiple, color, highlight_event_days, locale)
  File "/usr/lib/python3.5/site-packages/khal/calendar_display.py", line 142, in str_week
    multiple, color)
  File "/usr/lib/python3.5/site-packages/khal/calendar_display.py", line 108, in str_highlight_day
    if dcolor != '':
UnboundLocalError: local variable 'dcolor' referenced before assignment
```
Fix: uncomment the last line of the config file. The exception is not thrown any more. But I would prefer to not set a color on some of my calendars. So they don't draw as much attention and don't colorize the calendar overview to much but still get listed in the agenda (in the default terminal fg color).

**Comment by geier** [comment]
This is indeed a bug and will hopefully be fixed soon.

**Comment by geier** [comment]
Can you confirm this with current master (I can't)?

**Comment by lucc** [comment]
CNR either. Maybe I reported this still with version 0.7.0 ... sorry.
