### ISSUE TITLE
bug/feature request: Check data after edit

### ISSUE THREAD

**Issue by lucc** [geier/khal#335]
I would like the event editor in ikhal to do more checks on times (and other data?) for errors and either refuse to save or auto correct some mistakes. Currently it refuses to save if I enter an unparseable time (like `11`) but not if I enter an end time that is before the start time. The `new` command currently auto corrects in this case.

To reproduce use this mini config file:
```
[default]
  default_calendar = test
[calendars]
  [[test]]
    path = /tmp/khal_bug_report
```
Create two events:
```sh
khal -c test.conf new tomorrow 12:00 foo
khal -c test.conf new tomorrow 12:00 tomorrow 11:00 bar
```
Now I want to change the end of `foo`. I run `ikhal -c test.conf` and open the editor on `foo`. There I change the end time from `13:00` to `11:00` (or anything before 12:00) *but I do not change the date*. When I save this ikhal crashes with this exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 683, in start_pane
    loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 583, in keypress
    return super(EventEditor, self).keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3.5/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.5/site-packages/khal/ui/__init__.py", line 568, in save
    self.collection.update(self.event)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 330, in update
    self._calnames[event.calendar].update(event)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 142, in update
    self._dbtool.update(event.raw, event.href, event.etag)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 249, in update
    for vevent in sorted(vevents, key=sort_key):
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 242, in <genexpr>
    c in ical.walk() if c.name == u'VEVENT')
  File "/usr/lib/python3.5/site-packages/khal/khalendar/aux.py", line 151, in sanitize
    dtstart, dtend, duration=vevent.get('DURATION', None))
  File "/usr/lib/python3.5/site-packages/khal/khalendar/aux.py", line 168, in sanitize_timerange
    raise ValueError('The event\'s end time (DTEND) is older than '
ValueError: The event's end time (DTEND) is older than the event's start time (DTSTART).

```
But the invalid ical file is still written to disk and the next time I run `ikhal -c test.conf` or `khal -c test.conf agenda` or so I get this exception:
```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 233, in _update_vevent
    self._dbtool.update(event.raw, href=href, etag=etag)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 249, in update
    for vevent in sorted(vevents, key=sort_key):
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 242, in <genexpr>
    c in ical.walk() if c.name == u'VEVENT')
  File "/usr/lib/python3.5/site-packages/khal/khalendar/aux.py", line 151, in sanitize
    dtstart, dtend, duration=vevent.get('DURATION', None))
  File "/usr/lib/python3.5/site-packages/khal/khalendar/aux.py", line 168, in sanitize_timerange
    raise ValueError('The event\'s end time (DTEND) is older than '
ValueError: The event's end time (DTEND) is older than the event's start time (DTSTART).
warning: Skipping test/1VNPGHZ0BBTWEWQEGK66KR09IPW71PODBVD5.ics: The event's end time (DTEND) is older than the event's start time (DTSTART).
warning: This event will not be available in khal.
```
For comparison: the bar event was already automatically corrected by `khal new` because the end would be before start.  

I think that the editor should either refuse to save or adopt the auto correction behaviour from `khal new`.  At the very least khal should never write invalide ical files to disk.

**Comment by geier** [comment]
:crying_cat_face: I thought I had fixed this recently.

**Comment by lucc** [comment]
I am running 0.7.0 ... so I will check with the latest git and come back.

**Comment by lucc** [comment]
also present in 0.7.1.dev109+ng3fb3973.d20160213.

**Comment by geier** [comment]
Just to clarify: are you saving the event with <kbd>ctrl</kbd>+<kbd>Return</kbd>? After I have changed the end time, I cannot leave the end time field otherwise.

**Comment by geier** [comment]
But other invalid combinations still allow me to leave the edit fields :crying_cat_face:

**Comment by geier** [comment]
I've just pushed a change in branch `fix_335` ( de41f8826d19c7346f76222f39cc14a01ed8633f ), could you perhaps test if it behaves in a better way?

You can still trick it with pressing ctrl+Enter and there is a lot of duplicate code in there...

**Comment by lucc** [comment]
I was originally (still in 6044157) opening the editor, using the arrow keys to move to the end time field, edit it and leave it with the arrow keys. Then I move to the <save> button and press enter.

But now the times are adjusted to prevent me from leaving the time field with a value start>end.

**Comment by geier** [comment]
Does it work as you would expect?

**Comment by lucc** [comment]
Sadly it only works in some cases. If I try different things (use the arrow keys to move to the next field, move through one edit field with the left right keys, leave the edit field and come back) sometimes I can not leave an edit field and it is highlighted in red if I enter invalid data, and sometimes it is not highlighted and I can leave it. In such cases I can also hit the save button and get the two errors mentioned above.

Maybe the best point to check the data is when the user hits the <save> button (or the corresponding key combination). Because I also might want to edit the dates in such a way that for a short time (when switching from one edit field to the next) the dates would be not allowed. But I would not like to be blocked from leaving one field because I want to edit another field to make the date "legal" again.

**Comment by geier** [comment]
hopefully fixed with c4c0745ad735bd7211c8d29c1010f77893357d08

**Comment by lucc** [comment]
It works in some cases. I tried the following scenarios (always start with `khal -c test.conf new tomorrow 12:00 foo` and the move to the editor on foo)
1. change the `From` date to one day later, move down to `To` date (works), then I can not move our of the `To` date
2. change only the `From` time to something after the `To` time and move to <save> (works, the move is not blocked) If I save I get the above exception.

After some tests I assume that the current behavior is this: I am allowed to change all four date and time fields. If and only if I try to leave the `To` date field a check is made and I'm blocked from leafing this field if the combination of dates and times would be invalid. But the problem is that I can change one of the other three fields and move to the <save> button without going through the `To` date field and thus avoiding the check.

**Comment by geier** [comment]
Thank you for reporting this (again). On <kbd>enter</kbd> nothing really should happen...

**Comment by geier** [comment]
I believe I fixed this, please comment/reopen if I didn't (btw: <kbd>enter</kbd> should let a small pop-up calendar appear, I had forgotten about that...).

**Comment by lucc** [comment]
It seems to be fixed as far as I can tell. Thank you very much!!
