### ISSUE TITLE
events skipped over unlikely sqlite error

### ISSUE THREAD

**Issue by extmind** [geier/khal#364]
I noticed some missing events in my calendars, even after syncing. So I deleted khal.db to let khal regenerate it. This outputs a lot of errors like the following:
```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 233, in _update_vevent
    self._dbtool.update(event.raw, href=href, etag=etag)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 251, in update
    self._update_impl(vevent, href, self.calendar)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 329, in _update_impl
    self.sql_ex(recs_sql_s, stuple)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 208, in sql_ex
    self.cursor.execute(statement, stuple)
sqlite3.OperationalError: database or disk is full
warning: Skipping calendar/some-id.ics: database or disk is full
warning: This event will not be available in khal.
```
The same happens with khal-git:
```
debug: Updating some-id.ics because 1454089370733836800.000000000 != None
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 286, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 259, in update
    self._update_impl(vevent, href, calendar)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 386, in _update_impl
    self.sql_ex(recs_sql_s, stuple)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 215, in sql_ex
    self.cursor.execute(statement, stuple)
sqlite3.OperationalError: database or disk is full
warning: Skipping calendar/some-id.ics: database or disk is full
warning: This event will not be available in khal.
```
Considering the error message I've checked that the disk is certainly not full. Also khal.db seems to be not too big either:
```
240K	.khal/khal.db
```
Currently I have less events displayed in khal than before.

**Comment by geier** [comment]
This sounds interesting... I've never seen something like this before. Can you give us some more info, on your operating system, file system, etc?

**Comment by extmind** [comment]
Never mind this. Searching for this behaviour of sqlite I found out that it uses temporary files in /var/tmp which is on another partition which was close to be full.
