### ISSUE TITLE
Any recurring event breaks khal.

### ISSUE THREAD

**Issue by lucc** [geier/khal#374]
Today I noticed that all recurring events are not available in khal any longer. I'm in doubt if this is related to my system. Maybe you can reproduce it?

khal is at acc28ab.

config file:
```
[default]
  default_calendar = test
[calendars]
  [[test]]
    path = ~/tmp/khal_test
```
`~/tmp/khal_test` is an empty dir, I deleted the sqlite db. Then execute `PYTHONPATH=/path/to/khal/git/repo python -m khal -c test.conf new 12:00 something -r yearly`. I get this stack trace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/luc/vcs/khal/khal/__main__.py", line 25, in <module>
    main_khal()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/luc/vcs/khal/khal/cli.py", line 329, in new
    until=until.split(' ') if until is not None else None,
  File "/home/luc/vcs/khal/khal/controllers.py", line 190, in new_from_string
    collection.new(event)
  File "/home/luc/vcs/khal/khal/khalendar/khalendar.py", line 224, in new
    self._backend.update(event.raw, href, etag, calendar=calendar)
  File "/home/luc/vcs/khal/khal/khalendar/backend.py", line 260, in update
    self._update_impl(vevent, href, calendar)
  File "/home/luc/vcs/khal/khal/khalendar/backend.py", line 387, in _update_impl
    self.sql_ex(recs_sql_s, stuple)
  File "/home/luc/vcs/khal/khal/khalendar/backend.py", line 215, in sql_ex
    self.cursor.execute(statement, stuple)
sqlite3.OperationalError: database or disk is full
```

**Comment by hobarrera** [comment]
`sqlite3.OperationalError: database or disk is full`

Looks like it's the same problem as in #364. Can you check if your `/tmp` is full?

**Comment by lucc** [comment]
@hobarrera thanks yes that was the case. (Though it wasn't `/tmp` but `/var/tmp`.)
